# Generated by Django 5.0.1 on 2025-10-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_category_post_category_alter_post_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
