# Generated by Django 5.2.8 on 2025-11-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_alter_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
