# Generated by Django 5.2.8 on 2025-11-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_rename_auther_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
